package hello;

import java.util.Iterator;
import java.util.List;

import org.apache.commons.collections4.IteratorUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    Integer numberOfUsers;
    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path = "/update", consumes = "application/json; charset=UTF-8", produces = "application/json; charset=UTF-8")
    public void addNewUserFromButtonQuery(Model model, @ModelAttribute("name") String name
        , @ModelAttribute("email") String email)
    {
        System.out.println(name + "\\");
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        userRepository.save(user);

    }

    @PostMapping(value = "/postuser", consumes = "application/json; charset=UTF-8")
    public void addNewUserFromPost(@RequestBody User user)
    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        userRepository.save(user);
    }

    @GetMapping(value = "/updateusers")
    public String getAllUsers(Model model)
    {
        // This returns a JSON or XML with the users
        Iterator<User> allUsers = userRepository.findAll().iterator();
        List<User> userList = IteratorUtils.toList(allUsers);
        model.addAttribute(userList);
        return "#rows";
    }

    @PostMapping(value="/fun")
    public String addNewUserFromButton (Model model, @ModelAttribute("name") String name
            , @ModelAttribute("email") String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.out.println(name+"\\");
        System.out.println(email+"\\");
        if (!name.equals("")&&!email.equals(""))
        {
            User n = new User();
            n.setName(name);
            n.setEmail(email);
            userRepository.save(n);
        }
        return getAllUsersHTML(model);
    }

    @GetMapping(path="/fun")
    public String getAllUsersHTML(Model model) {
        // This returns a JSON or XML with the users
        Iterator<User> allUsers=userRepository.findAll().iterator();
        List<User>  userList= IteratorUtils.toList(allUsers);
        model.addAttribute(userList);
        return "greeting";
    }



}